version: "3.9"
services:
  api:
    build: ..
    image: details-share-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/scripts
    command: uvicorn main:scripts --host 0.0.0.0 --port 8000 --reload --reload-dir /scripts
    environment:
      - WATCHFILES_FORCE_POLLING=true
